In [2]:
import numpy as np
import pandas as pd
from datacleaner import autoclean

train = pd.read_csv('data/train.csv', na_values=['NA'])
test_x = pd.read_csv('data/test.csv', na_values=['NA'])

train_x = train.drop('SalePrice', 1)
train_y = train["SalePrice"]

In [3]:
# Identify columns with low variance
for col in train:
    print col, "\n"
    print train[col].describe()
    print "\n\n"

Id

count    1460.000000
mean      730.500000
std       421.610009
min         1.000000
25%       365.750000
50%       730.500000
75%      1095.250000
max      1460.000000
Name: Id, dtype: float64



MSSubClass

count    1460.000000
mean       56.897260
std        42.300571
min        20.000000
25%        20.000000
50%        50.000000
75%        70.000000
max       190.000000
Name: MSSubClass, dtype: float64



MSZoning

count     1460
unique       5
top         RL
freq      1151
Name: MSZoning, dtype: object



LotFrontage

count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%              NaN
50%              NaN
75%              NaN
max       313.000000
Name: LotFrontage, dtype: float64



LotArea

count      1460.000000
mean      10516.828082
std        9981.264932
min        1300.000000
25%        7553.500000
50%        9478.500000
75%       11601.500000
max      215245.000000
Name: LotArea, dtype: float64



Street

count     1460
unique       2
top       Pave
freq      1454
Name: Street, dtype: object



Alley

count       91
unique       2
top       Grvl
freq        50
Name: Alley, dtype: object



LotShape

count     1460
unique       4
top        Reg
freq       925
Name: LotShape, dtype: object



LandContour

count     1460
unique       4
top        Lvl
freq      1311
Name: LandContour, dtype: object



Utilities

count       1460
unique         2
top       AllPub
freq        1459
Name: Utilities, dtype: object



LotConfig

count       1460
unique         5
top       Inside
freq        1052
Name: LotConfig, dtype: object



LandSlope

count     1460
unique       3
top        Gtl
freq      1382
Name: LandSlope, dtype: object



Neighborhood

count      1460
unique       25
top       NAmes
freq        225
Name: Neighborhood, dtype: object



Condition1

count     1460
unique       9
top       Norm
freq      1260
Name: Condition1, dtype: object



Condition2

count     1460
unique       8
top       Norm
freq      1445
Name: Condition2, dtype: object



BldgType

count     1460
unique       5
top       1Fam
freq      1220
Name: BldgType, dtype: object



HouseStyle

count       1460
unique         8
top       1Story
freq         726
Name: HouseStyle, dtype: object



OverallQual

count    1460.000000
mean        6.099315
std         1.382997
min         1.000000
25%         5.000000
50%         6.000000
75%         7.000000
max        10.000000
Name: OverallQual, dtype: float64



OverallCond

count    1460.000000
mean        5.575342
std         1.112799
min         1.000000
25%         5.000000
50%         5.000000
75%         6.000000
max         9.000000
Name: OverallCond, dtype: float64



YearBuilt

count    1460.000000
mean     1971.267808
std        30.202904
min      1872.000000
25%      1954.000000
50%      1973.000000
75%      2000.000000
max      2010.000000
Name: YearBuilt, dtype: float64



YearRemodAdd

count    1460.000000
mean     1984.865753
std        20.645407
min      1950.000000
25%      1967.000000
50%      1994.000000
75%      2004.000000
max      2010.000000
Name: YearRemodAdd, dtype: float64



RoofStyle

count      1460
unique        6
top       Gable
freq       1141
Name: RoofStyle, dtype: object



RoofMatl

count        1460
unique          8
top       CompShg
freq         1434
Name: RoofMatl, dtype: object



Exterior1st

count        1460
unique         15
top       VinylSd
freq          515
Name: Exterior1st, dtype: object



Exterior2nd

count        1460
unique         16
top       VinylSd
freq          504
Name: Exterior2nd, dtype: object



MasVnrType

count     1452
unique       4
top       None
freq       864
Name: MasVnrType, dtype: object



MasVnrArea

count    1452.000000
mean      103.685262
std       181.066207
min         0.000000
25%              NaN
50%              NaN
75%              NaN
max      1600.000000
Name: MasVnrArea, dtype: float64



ExterQual

count     1460
unique       4
top         TA
freq       906
Name: ExterQual, dtype: object



ExterCond

count     1460
unique       5
top         TA
freq      1282
Name: ExterCond, dtype: object



Foundation

count      1460
unique        6
top       PConc
freq        647
Name: Foundation, dtype: object



BsmtQual

count     1423
unique       4
top         TA
freq       649
Name: BsmtQual, dtype: object



BsmtCond

count     1423
unique       4
top         TA
freq      1311
Name: BsmtCond, dtype: object



BsmtExposure

count     1422
unique       4
top         No
freq       953
Name: BsmtExposure, dtype: object



BsmtFinType1

count     1423
unique       6
top        Unf
freq       430
Name: BsmtFinType1, dtype: object



BsmtFinSF1

count    1460.000000
mean      443.639726
std       456.098091
min         0.000000
25%         0.000000
50%       383.500000
75%       712.250000
max      5644.000000
Name: BsmtFinSF1, dtype: float64



BsmtFinType2

count     1422
unique       6
top        Unf
freq      1256
Name: BsmtFinType2, dtype: object



BsmtFinSF2

count    1460.000000
mean       46.549315
std       161.319273
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max      1474.000000
Name: BsmtFinSF2, dtype: float64



BsmtUnfSF

count    1460.000000
mean      567.240411
std       441.866955
min         0.000000
25%       223.000000
50%       477.500000
75%       808.000000
max      2336.000000
Name: BsmtUnfSF, dtype: float64



TotalBsmtSF

count    1460.000000
mean     1057.429452
std       438.705324
min         0.000000
25%       795.750000
50%       991.500000
75%      1298.250000
max      6110.000000
Name: TotalBsmtSF, dtype: float64



Heating

count     1460
unique       6
top       GasA
freq      1428
Name: Heating, dtype: object



HeatingQC

count     1460
unique       5
top         Ex
freq       741
Name: HeatingQC, dtype: object



CentralAir

count     1460
unique       2
top          Y
freq      1365
Name: CentralAir, dtype: object



Electrical

count      1459
unique        5
top       SBrkr
freq       1334
Name: Electrical, dtype: object



1stFlrSF

count    1460.000000
mean     1162.626712
std       386.587738
min       334.000000
25%       882.000000
50%      1087.000000
75%      1391.250000
max      4692.000000
Name: 1stFlrSF, dtype: float64



2ndFlrSF

count    1460.000000
mean      346.992466
std       436.528436
min         0.000000
25%         0.000000
50%         0.000000
75%       728.000000
max      2065.000000
Name: 2ndFlrSF, dtype: float64



LowQualFinSF

count    1460.000000
mean        5.844521
std        48.623081
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       572.000000
Name: LowQualFinSF, dtype: float64



GrLivArea

count    1460.000000
mean     1515.463699
std       525.480383
min       334.000000
25%      1129.500000
50%      1464.000000
75%      1776.750000
max      5642.000000
Name: GrLivArea, dtype: float64



BsmtFullBath

count    1460.000000
mean        0.425342
std         0.518911
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         3.000000
Name: BsmtFullBath, dtype: float64



BsmtHalfBath

count    1460.000000
mean        0.057534
std         0.238753
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         2.000000
Name: BsmtHalfBath, dtype: float64



FullBath

count    1460.000000
mean        1.565068
std         0.550916
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         3.000000
Name: FullBath, dtype: float64



HalfBath

count    1460.000000
mean        0.382877
std         0.502885
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         2.000000
Name: HalfBath, dtype: float64



BedroomAbvGr

count    1460.000000
mean        2.866438
std         0.815778
min         0.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         8.000000
Name: BedroomAbvGr, dtype: float64



KitchenAbvGr

count    1460.000000
mean        1.046575
std         0.220338
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: KitchenAbvGr, dtype: float64



KitchenQual

count     1460
unique       4
top         TA
freq       735
Name: KitchenQual, dtype: object



TotRmsAbvGrd

count    1460.000000
mean        6.517808
std         1.625393
min         2.000000
25%         5.000000
50%         6.000000
75%         7.000000
max        14.000000
Name: TotRmsAbvGrd, dtype: float64



Functional

count     1460
unique       7
top        Typ
freq      1360
Name: Functional, dtype: object



Fireplaces

count    1460.000000
mean        0.613014
std         0.644666
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: Fireplaces, dtype: float64



FireplaceQu

count     770
unique      5
top        Gd
freq      380
Name: FireplaceQu, dtype: object



GarageType

count       1379
unique         6
top       Attchd
freq         870
Name: GarageType, dtype: object



GarageYrBlt

count    1379.000000
mean     1978.506164
std        24.689725
min      1900.000000
25%              NaN
50%              NaN
75%              NaN
max      2010.000000
Name: GarageYrBlt, dtype: float64



GarageFinish

count     1379
unique       3
top        Unf
freq       605
Name: GarageFinish, dtype: object



GarageCars

count    1460.000000
mean        1.767123
std         0.747315
min         0.000000
25%         1.000000
50%         2.000000
75%         2.000000
max         4.000000
Name: GarageCars, dtype: float64



GarageArea

count    1460.000000
mean      472.980137
std       213.804841
min         0.000000
25%       334.500000
50%       480.000000
75%       576.000000
max      1418.000000
Name: GarageArea, dtype: float64



GarageQual

count     1379
unique       5
top         TA
freq      1311
Name: GarageQual, dtype: object



GarageCond

count     1379
unique       5
top         TA
freq      1326
Name: GarageCond, dtype: object



PavedDrive

count     1460
unique       3
top          Y
freq      1340
Name: PavedDrive, dtype: object



WoodDeckSF

count    1460.000000
mean       94.244521
std       125.338794
min         0.000000
25%         0.000000
50%         0.000000
75%       168.000000
max       857.000000
Name: WoodDeckSF, dtype: float64



OpenPorchSF

count    1460.000000
mean       46.660274
std        66.256028
min         0.000000
25%         0.000000
50%        25.000000
75%        68.000000
max       547.000000
Name: OpenPorchSF, dtype: float64



EnclosedPorch

count    1460.000000
mean       21.954110
std        61.119149
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       552.000000
Name: EnclosedPorch, dtype: float64



3SsnPorch

count    1460.000000
mean        3.409589
std        29.317331
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       508.000000
Name: 3SsnPorch, dtype: float64



ScreenPorch

count    1460.000000
mean       15.060959
std        55.757415
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       480.000000
Name: ScreenPorch, dtype: float64



PoolArea

count    1460.000000
mean        2.758904
std        40.177307
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       738.000000
Name: PoolArea, dtype: float64



PoolQC

count      7
unique     3
top       Gd
freq       3
Name: PoolQC, dtype: object



Fence

count       281
unique        4
top       MnPrv
freq        157
Name: Fence, dtype: object



MiscFeature

count       54
unique       4
top       Shed
freq        49
Name: MiscFeature, dtype: object



MiscVal

count     1460.000000
mean        43.489041
std        496.123024
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      15500.000000
Name: MiscVal, dtype: float64



MoSold

count    1460.000000
mean        6.321918
std         2.703626
min         1.000000
25%         5.000000
50%         6.000000
75%         8.000000
max        12.000000
Name: MoSold, dtype: float64



YrSold

count    1460.000000
mean     2007.815753
std         1.328095
min      2006.000000
25%      2007.000000
50%      2008.000000
75%      2009.000000
max      2010.000000
Name: YrSold, dtype: float64



SaleType

count     1460
unique       9
top         WD
freq      1267
Name: SaleType, dtype: object



SaleCondition

count       1460
unique         6
top       Normal
freq        1198
Name: SaleCondition, dtype: object



SalePrice

count      1460.000000
mean     180921.195890
std       79442.502883
min       34900.000000
25%      129975.000000
50%      163000.000000
75%      214000.000000
max      755000.000000
Name: SalePrice, dtype: float64

C:\Anaconda2\lib\site-packages\numpy\lib\function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

In [4]:
# Preprocessing
from sklearn import preprocessing

In [5]:
def del_missing(data):
    print 'del_missing'
    
    data[data < 0] = np.nan
    #print type(np.nan)
    #print data
    
    #if NA:
    #    data['LotFrontage'][10] = ''

def average_missing(data):
    print 'average_missing'

def clean_data(data, handle_missing_fn=del_missing):
    handle_missing_fn(data)

In [6]:
clean_data(data)

NameError: name 'data' is not defined

In [6]:
Outliers!

SyntaxError: invalid syntax (<ipython-input-6-2d6561d7f13e>, line 1)

In [7]:
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor
boston = load_boston()
regressor = DecisionTreeRegressor(random_state=0)
cross_val_score(regressor, boston.data, boston.target, cv=10)

ImportError: No module named model_selection